services:
  spark-master:
    build: spark/spark
    container_name: spark-master
    hostname: spark
    expose:
      - 22
    ports:
      - '7077:7077'   # Spark port
      - '8077:8077'   # Spark master web ui port
      - '18080:18080' # Spark history web ui port
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_MASTER_WEBUI_PORT: 8077
      SPARK_MASTER_PORT: 7077
      SPARK_HOME: /opt/spark
      SPARK_WORKLOAD: master
      SPARK_NO_DAEMONIZE: true
      SPARK_PUBLIC_DNS: 192.168.0.200
    depends_on:
      - spark-worker-01
      - spark-worker-02
    command: ["start-master.sh -p 7077 --webui-port 8077"]
    networks:
      - public
    restart:
      always

  spark-worker-01:
    build: spark/spark
    container_name: spark-worker-01
    hostname: spark-worker-01
    expose:
      - 22
    ports:
      - '8001:8001' # Spark worker web ui port
    environment:
      SPARK_MASTER: "spark://spark:7077"
      SPARK_WORKER_PORT: 7001
      SPARK_WORKLOAD: worker
      SPARK_LOCAL_IP: spark-worker-01
      SPARK_WORKER_CORES: 6
      SPARK_WORKER_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_NO_DAEMONIZE: true
      SPARK_PUBLIC_DNS: 192.168.0.200
    command: ["start-worker.sh spark://spark:7077 --webui-port 8001"]
    networks:
      - public
    restart: always

  spark-worker-02:
    build: spark/spark
    container_name: spark-worker-02
    hostname: spark-worker-02
    expose:
      - 22
    ports:
      - '8002:8002' # Spark worker web ui port
    environment:
      SPARK_MASTER: "spark://spark:7077"
      SPARK_WORKER_PORT: 7002
      SPARK_WORKLOAD: worker
      SPARK_LOCAL_IP: spark-worker-02
      SPARK_WORKER_CORES: 6
      SPARK_WORKER_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_NO_DAEMONIZE: true
      SPARK_PUBLIC_DNS: 192.168.0.200
    command: ["start-worker.sh spark://spark:7077 --webui-port 8002"]
    networks:
      - public
    restart: always
