services:
  playground:
    build: playground/
    container_name: playground
    volumes:
      - ./data/playground/notebooks:/var/lib/fxttr/notebooks
    ports:
      - '8888:8888'
    networks:
      - public
    command: 
      - notebook
    restart:
      always

  trino:
    build: trino/
    container_name: trino
    volumes:
      - ./trino/conf/trino.pass:/trino.pass
      - ./trino/conf/cert.pem:/cert.pem
    ports:
      - '8060:8060' # Trino
      - '8063:8063' # Trino
    networks:
      - public
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

networks:
  public:
    driver: bridge