%TAG ! dsadm
---
!
repos:
  - name: "trino"
    url: "https://trinodb.github.io/charts"

plugins:
  - name: "helm-secrets"
    url: "https://github.com/jkroepke/helm-secrets --version v4.6.2"

charts:
  - name: "trino-cluster"
    namespace: "trino"
    repo: "trino/trino"
    values: "trino.yaml"

operators:
  - name: "clickhouse"
    namespace: "clickhouse"
    definition: "k8s/operator/clickhouse.yaml"
    deployments: ["clickhouse.yaml"]