apiVersion: v1
kind: Secret
metadata:
    name: trino-secret-env
    labels:
        app: trino
type: Opaque
data:
    MINIO_ACCESS_KEY: bWFycmVybw==
    MINIO_SECRET_KEY: Ri5nOThfIURSX2c4
    CLICKHOUSE_USERNAME: ZGVmYXVsdA==
    CLICKHOUSE_PASSWORD: Ri5nOThfIURSX2c4
