apiVersion: v1
kind: Secret
metadata:
    name: trino-secret-env
    labels:
        app: trino
type: Opaque
data:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:JUnMN9nZUyLzXtTT,iv:N3+TV8G1xmdmDWu+eMp7KRWICSn7FxHVaO/+vz6xs8U=,tag:K5hk0eU5QdRgnfIBbbvvQA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:TnQdHcF30aRejEvvIz4CiQ==,iv:cTKKo4blvfAKEeAR4SKp/OqCk1qbYibVl3flTvX++lc=,tag:uuDMWjYb3xsebofGHAWO7Q==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:CMurPiMFDQdd0A3d,iv:GqiGUiNmTt2DV/3KjYAeVENmkX7bDExQRPLLUXJu1PQ=,tag:WeDWqdLZsL2clMcl4KsZAA==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:2J3kjAPUUd6rUa8E,iv:nHldHKhz0BZxSrtnyMMmTJJPznjrb+ie0djlD0/MqfM=,tag:RSCAE52g4YGGbU103pBRAw==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:NHqsG0Y/6/LdKUcNTypXFg==,iv:4CHk61YSMaLy4FNkUK2N+cthz1I1fWsh9B7L25t5AqA=,tag:HkC8XXpYjphJU6WOKPlOTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QzYwNXpoTzZFbUpqODFn
            Vnd4VGk3cFhNUm9kTUh6WGRDSXFFWVYrM0I0Cjljd2xwdmRGMkZxUU52Y1QxR1VB
            UW1jZjg4MGxYL3BVdHRKV3ZEd0RVOGsKLS0tIFBWMnZCallIM0ZSZ21yRzZkZHU2
            WkovZGd3Q28ySXg2a0g4TkVSWWxYbmsKS0Etz5B+RWQrsmNmXOnp2zodxRPlfAQ4
            1yZeD9LQo8T5uj0VRgqL+hQqakznZgW26wVIzlqxzAxd3L1K+ctWKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:LnrpOFyJuYnUXST5obwXpTq6II31v4xz+zkD4A5A+HMJrGxSqTvZFkDaYp8JI/GPRhUKSWn/D1VyG5p1MXlIu+NB7TNuM1AuSYs7yU+2vVhsIt1yF9H+j70jCNg/1PENHyRHP6jbD4J/0TmD3qqa/N/FcS/ZCWfNkPWfxF6MJJo=,iv:08DxF902wlFgiThVtvYtG0FzDDQvMzWyvee+wHhu0ZQ=,tag:W/Sdtm6AHIR+quqQLgMyZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
