apiVersion: v1
kind: Secret
metadata:
    name: trino-secret-env
    labels:
        app: trino
type: Opaque
data:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:sPtw1pyeDQD7ZszE,iv:ZLyCAQDr8/cghI2dFvVuc0gIGZW6SxiupH5WJrjLBHM=,tag:FidupoS9BlmcuntF4UA1Xg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:RnPkvR8+KMpn3b8RmVIC7g==,iv:3CilFqKnEVLXu3LbsXjZ2TybIKGM/1GucUmbmWBULmI=,tag:cShLULrxRxe9Fa/JlRcaPA==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:d42WhY8ImFzbrtay,iv:P21KjP4gNNMOWxJwDPbER2t0zJ+y+O/wKQ1miZYv/D8=,tag:JBkyqKes7hxcbnY1RuDtpA==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:+QXebgCtsZZMHQrS,iv:BufQ6l40Gk43weGjOu0KUhQDiNqVDbGEDwxl/3MCvH4=,tag:eIq6EK+yT7SgI/JYWwCxow==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:D55Tcm1a9CJvJdN3nEZ26A==,iv:FhQbkM79uxW2/jIdvT2tG6oNq1zcZOc2iKcBNNLoiqI=,tag:kNTMO0mPS7gjTnAH+xN9pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK0x3ZGhKMXdKTG1DeVVq
            ekhYS1pLRkJhRytnbDNzUEQ1eEtrMmVRVFR3CjMrR1IxTllESzNjYXNUWVU0eHFl
            K1FPelE5T3ArUVdpcTN3cm1JUGkzS2cKLS0tIFhHU2dHYk1NY25ib0djVERxUXhs
            bU1aQWI1TTdNU2paV1Y3amVTaHIzVFkKV4qgjK5uIPABYJBRkOmDgTFrm+GDfWFH
            jLmCKUPDNcPn+5DKaiYUPVULVznBWPY7Y4/cjwBVex730cDg+8QEwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T20:21:37Z"
    mac: ENC[AES256_GCM,data:ko6FI83WAYhD67HRJl13uNuuCjjG/TnDLL3Xu/mgHbngpSQ4KULK2W+iNDA+3clN5K9TyIxPdlUSSS+f7G0MaM82+5zY9xLMm/QR8GwGEQSEGqxxMM8eiTA5k61KiiAuLfySWTlpkmz9/unBP+pDcU1f9ivC+KeyKUhODwpjd4k=,iv:8/FFgIbPsRIQmre2WEwRCqtVaT+TiMSmgPaj8obVfUs=,tag:+5kyGd+4vY0Nk1Vbixo6Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
