services:
  hive_metastore_db:
    image: postgres:16
    hostname: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
      POSTGRES_DB: metastore
    volumes:
      - hive_metastore_db_data:/var/lib/postgresql/data
      - ./hive/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    networks:
      - metastore-internal
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]

  hive_metastore:
    build: hive/
    hostname: metastore
    ports:
      - '9083:9083'
      - '10000:10000'
    volumes:
      - hive_metastore_data:/opt/hive/data/warehouse
    networks:
      - metastore-internal
      - public
    environment:
      DATABASE_HOST: hive_metastore_db
      DATABASE_DB: metastore
      DATABASE_USER: hive
      DATABASE_PASSWORD: hive123
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: access123
      S3_SECRET_KEY: secret123
    depends_on:
      -  hive_metastore_db
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9083"

networks:
  metastore-internal:

volumes:
  hive_metastore_db_data:
  hive_metastore_data:
