services:
  dagster_postgresql:
    image: postgres:16
    container_name: dagster-postgresql
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_DATABASE_USERNAME}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_DATABASE_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_DATABASE}
    networks:
      - dagster-internal

  dagster_webserver:
    build: dagster/dagster
    container_name: dagster_webserver
    restart: on-failure
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3070"
      - -w
      - workspace.yaml
    expose:
      - "3070"
    ports:
      - "3070:3070"
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_DATABASE_USERNAME}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_DATABASE_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_DATABASE}
    volumes:
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./pipelines/home:/opt/dagster/dagster_home/
    networks:
      - dagster-internal
      - public
    depends_on:
      - dagster_postgresql

  dagster_daemon:
    build: dagster/dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster-daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_DATABASE_USERNAME}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_DATABASE_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_DATABASE}
    volumes:
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./pipelines/home:/opt/dagster/dagster_home/
    networks:
      - dagster-internal
    depends_on:
      - dagster_postgresql

networks:
  dagster-internal:

volumes:
  nessie_db_data:
  nessie_data: