apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

helmCharts:
- name: altinity-clickhouse-operator
  repo: https://altinity.github.io/clickhouse-operator
  releaseName: altinity-clickhouse-operator
  version: 0.24.1