services:
  dagster_postgresql:
    image: postgres:16
    container_name: dagster_postgresql
    hostname: dagster_postgresql
    networks:
      - dagster-internal
      - public
    env_file:
      - env/dagster.env
      - env/pipeline.env

  dagster_webserver:
    build: dagster/dagster
    container_name: dagster_webserver
    hostname: dagster_webserver
    restart: on-failure
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3070"
      - -w
      - workspace.yaml
    expose:
      - "3070"
    ports:
      - "3070:3070"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./pipelines/home:/opt/dagster/dagster_home/
    networks:
      - dagster-internal
      - public
    depends_on:
      - dagster_postgresql
    env_file:
      - env/dagster.env
      - env/pipeline.env

  dagster_daemon:
    build: dagster/dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    hostname: dagster_daemon
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./pipelines/home:/opt/dagster/dagster_home/
    networks:
      - dagster-internal
      - public
    depends_on:
      - dagster_postgresql
    env_file:
      - env/dagster.env
      - env/pipeline.env

networks:
  dagster-internal:

volumes:
  nessie_db_data:
  nessie_data: