services:
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    networks:
      - public
      - nessie-internal
    environment:
      QUARKUS_HTTP_PORT: 19120
      QUARKUS_PROFILE: prod
      NESSIE_VERSION_STORE_TYPE: JDBC
    volumes:
      - nessie_data:/var/lib/nessie/data
    env_file:
      - env/nessie.env

  nessie-db:
    image: postgres:16
    hostname: nessie-db
    expose:
      - 5432
    networks:
      - nessie-internal
    volumes:
      - nessie_db_data:/var/lib/postgresql/data
    env_file:
      - env/nessie.env

networks:
  nessie-internal:

volumes:
  nessie_db_data:
  nessie_data:
