apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
- name: dagster
  repo: https://dagster-io.github.io/helm
  releaseName: dagster
  includeCRDs: true
  valuesInline:
    dagster-user-deployments:
      enabled: true