apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - deployment.yaml
  - pv.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml

helmCharts:
- name: dagster
  repo: https://dagster-io.github.io/helm
  releaseName: dagster
  includeCRDs: true
  valuesInline:
    global:
      postgresqlSecretName: dagster-database-creds
    dagster-user-deployments:
      enabled: true
    generatePostgresqlPasswordSecret: false
    postgresql:
      enabled: false # this disables the internal postgresql. We are using the external one.
      image:
        repository: "library/postgres"
        tag: "14.6"
        pullPolicy: IfNotPresent
      postgresqlHost: "dagster-database"
      postgresqlUsername: dagster
      postgresqlDatabase: "dagster"
      postgresqlParams: {}
      postgresqlScheme: ""
      volumePermissions:
        enabled: true
      service:
        port: 5432
