apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-database-pv
  
  labels:
    type: local
    app: dagster-database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/mnt/dagster/database
