apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-database-pvc
  
  labels:
    app: dagster-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
