apiVersion: v1
kind: Secret
metadata:
    name: dagster-database-creds
    labels:
        app: dagster-database
type: Opaque
data:
    postgresql-password: ENC[AES256_GCM,data:P6ndJPFSoDi88+h6tBY0s2814H1gS/XP,iv:O8puMo0Q4eg+Iv/Oqti0tfG68+qiKKEEy3tgEJFiL1I=,tag:kgSLv6zC0hj9Mq8y/Egdag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdHhXOEp5WGpzSDAvQzNP
            WjBlL0NrLzZlR3B4NU5Zdkl1Tys3TDdhQmdvCjBBaU5LSk9CcFVxSnZoWXlEWTFo
            UHZzb20xdnZzV0JlczVpb1ZuaEl5ZzQKLS0tIGk5SzN1d2FpbFlCS01EV3JUZ3o4
            WXdLRzM5UmpiVW9lcEhIbVRLWnlGdE0KcDsU/UpQ1d8fHSb+9S1VAeqU7ZAuP+q5
            NvNpRO1gyoxyzSj2WVk8yWaQF8NNUE0q8bEEKdqaM+wCt70TKR5Z5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:QpwT+WCNPeX+7hPiacWz2aVEinpDDr/Vkk+ezQvLQOD18GucCJPd8P3XhtliByzBcZYtl4tDMzOXW7VO+9N47SHRr7MrNwTK3MVDi6PtlCaVRlXlpe3kyovvfRY5wR58b1Th76eHpBqu/A4q4usA2DPsf3PQ+TWzZ+aXpPByIts=,iv:3kk9X+6dVlb6zbIc5mMU9S9z0EIrVaAP8wdzIHNgs4Y=,tag:WwfDZs2l7VLde85fjn+trQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
