apiVersion: v1
kind: Service
metadata:
  name: dagster-database
  
  labels:
    app: dagster-database
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: dagster-database
