apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-data-pv
  namespace: pideu-datastack
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/clickhouse/data
