apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse-cluster
spec:
  defaults:
    templates:
      volumeClaimTemplate: pvc-template
  configuration:
    users:
      marrero/password: 
        valueFrom:
          secretKeyRef:
            name: clickhouse-user-secret
            key: password
      marrero/networks/ip:
        - 0.0.0.0/24
    settings:
          s3/warehouse/endpoint: "http://minio:9000/warehouse/"
          s3/warehouse/secret_access_key:
            valueFrom:
              secretKeyRef:
                name: storage-user
                key: CONSOLE_ACCESS_KEY
          s3/warehouse/access_key:
            valueFrom:
              secretKeyRef:
                name: storage-user
                key: CONSOLE_SECRET_KEY
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers
        - host: zookeeper-1.zookeepers
        - host: zookeeper-2.zookeepers
    clusters:
      - name: cluster1
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-template
          volumeClaimTemplate: pvc-template
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "1"
                limits:
                  memory: "8Gi"
                  cpu: "4"
              volumeMounts:
                - name: clickhouse-data
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: pvc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "20Gi"
