apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse-cluster
spec:
  defaults:
    templates:
      volumeClaimTemplate: pvc-template
  configuration:
    users:
      default/password: 1234
      default/networks/ip:
        - 0.0.0.0/24
    zookeeper:
      nodes:
        - host: zookeeper1.datastack.svc.cluster.local
        - host: zookeeper2.datastack.svc.cluster.local
    clusters:
      - name: cluster1
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-template
          volumeClaimTemplate: pvc-template
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "1"
                limits:
                  memory: "your-memory-limit-Gi"
                  cpu: "your-cpu-limit"
              volumeMounts:
                - name: clickhouse-data
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: pvc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "20Gi"
