apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-operator-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:X0njqHUNdmV1jDoxHaa1OL3awA==,iv:6MtaR6p/B37sKk4N5CJ5tMGsK3N/q3DreU5gdglQsv4=,tag:16ujsWSTLP+SXNSDbeDjiw==,type:str]
    password: ENC[AES256_GCM,data:ID8c1MTkbDfebof2y2U0c9oj/Wm/mw9p8Q==,iv:EaECKCAEiLJIK14Dx5tIC7ImXEBa4nyV8QGmTf6T7wk=,tag:/+7qOiGksmaG7M8WODjqNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMnBEKzIwSUtvMDkxSzdB
            dkM0Z2x1UEE5RStGTDBjSEFjMEhFR0I3M0dFCmZVSzZnb1BxMk9CZk14UHVkclN2
            czNpTk1kT0JreWRPSER4MTBJWEhEZE0KLS0tIFhPeFVXeU43QVF6b0h1ZUNpWXZy
            MjBYd2ZZYkRqaXJHUmpWN3Q3M2pDcFkKexMvNLMyFLARYxO48Wq04WrIPP+tdp7k
            cmGuNAngFm1E3gh4J7TgRtDbKjm+klAGklpaX2q7vSb7MleMYAkyng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:Zj7SEBAvZ/4T2Iga6wGw1bugTYzcmxH+3GhFsropt7O+vtH27vy32aqY/Fa+6IkoPerZBxBh9PzPNQ8wkt7Wh8oBoTR1Cdc1J42YltFbncCrqU+UrOVDMfaBxOpSQ9o1RmEBOvjp3KFmnM9NjlWq165ORs7BYvfSOvWmsCf29Ho=,iv:ED7/+YXkhxr//OwjnGs75VIu+oTujFXwGFTqVxzwUic=,tag:RheBnT30efJw+MqTNtYiSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-user-secret
type: Opaque
data:
    password: ENC[AES256_GCM,data:6WNJIxoSr7KT2ZUVg+RuIg==,iv:n6dj1LrNrhz/9L1YeDtbi0FD+nUEezzjgGJHRA0qOqk=,tag:2n2/o1lNluGq0J5BzROCUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMnBEKzIwSUtvMDkxSzdB
            dkM0Z2x1UEE5RStGTDBjSEFjMEhFR0I3M0dFCmZVSzZnb1BxMk9CZk14UHVkclN2
            czNpTk1kT0JreWRPSER4MTBJWEhEZE0KLS0tIFhPeFVXeU43QVF6b0h1ZUNpWXZy
            MjBYd2ZZYkRqaXJHUmpWN3Q3M2pDcFkKexMvNLMyFLARYxO48Wq04WrIPP+tdp7k
            cmGuNAngFm1E3gh4J7TgRtDbKjm+klAGklpaX2q7vSb7MleMYAkyng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:Zj7SEBAvZ/4T2Iga6wGw1bugTYzcmxH+3GhFsropt7O+vtH27vy32aqY/Fa+6IkoPerZBxBh9PzPNQ8wkt7Wh8oBoTR1Cdc1J42YltFbncCrqU+UrOVDMfaBxOpSQ9o1RmEBOvjp3KFmnM9NjlWq165ORs7BYvfSOvWmsCf29Ho=,iv:ED7/+YXkhxr//OwjnGs75VIu+oTujFXwGFTqVxzwUic=,tag:RheBnT30efJw+MqTNtYiSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
