apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-operator-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bp2/VjjT6k0s2BxpXc4aFXcd0g==,iv:3penxj7+sS3VChifQgcJ5jBJBbqzn8N4MWtFihs9+rM=,tag:fQuwaJRuOn/ipY8Ijt26AQ==,type:str]
    password: ENC[AES256_GCM,data:Q6wlDwAma1UXyT66katWMoGtApa7nyT2vA==,iv:eUZIapIbmmiHmiwV15QarJ0geVDIGRIn4aXrkQt6YdA=,tag:fqVOZTXMvK6FL/ljN/bAcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZlRLNEo0dTE5cEZ1YTVj
            VHFmczZpK1E5NDkydGZNbkJwR3pDSFhHYzNVCmxrclJXYVFOSEVNaUdXcGc1VVUz
            NHJaNml5d0tFMUZza0QvSnE1WlNYdUEKLS0tIDFTVVBQaGl4Wlk2Y3plSmtzUFl6
            QWpFd0NvUUM1WG1kaUpNaHlhU3BkRUEKPANnxJ2hYAMWcKAf5aKZTJ2ib3bv5+7u
            08LW6cU+v6tq8fuGrYHQ6CzP3Ll4m5V8TSozP8Rg/6xIwsivUsM19A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:oDXi9AxjyOaHJw4kA21Bx2Falw/PIfPZ0cDJaL+DnXSduhWQJMICiWyMFrFsLzMMNyJxsRcfnChnANzyvqhlouvvQ9OvbcZ1c/d+/S+l6DtJVkr6jdkKJ/ACl68RQteyIr+KvgQiz3hj/zyUTiyfJ1HJ06WYjYkeqNJvsgthqH8=,iv:ycyV8mgHLacekSg53PiFG0Koa2ycQmKpinUdP38h66w=,tag:uX01/cXStFow+Uqo6BNkIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-user-secret
type: Opaque
data:
    password: ENC[AES256_GCM,data:yawxqtxGaTgjbAt04yPxJA==,iv:wxhmKkiHZdeSyWqDG4k7++WZeOG0rsEfxZ24SAzZ98I=,tag:PR+PJY95QFUaqAaPqTUzlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZlRLNEo0dTE5cEZ1YTVj
            VHFmczZpK1E5NDkydGZNbkJwR3pDSFhHYzNVCmxrclJXYVFOSEVNaUdXcGc1VVUz
            NHJaNml5d0tFMUZza0QvSnE1WlNYdUEKLS0tIDFTVVBQaGl4Wlk2Y3plSmtzUFl6
            QWpFd0NvUUM1WG1kaUpNaHlhU3BkRUEKPANnxJ2hYAMWcKAf5aKZTJ2ib3bv5+7u
            08LW6cU+v6tq8fuGrYHQ6CzP3Ll4m5V8TSozP8Rg/6xIwsivUsM19A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:oDXi9AxjyOaHJw4kA21Bx2Falw/PIfPZ0cDJaL+DnXSduhWQJMICiWyMFrFsLzMMNyJxsRcfnChnANzyvqhlouvvQ9OvbcZ1c/d+/S+l6DtJVkr6jdkKJ/ACl68RQteyIr+KvgQiz3hj/zyUTiyfJ1HJ06WYjYkeqNJvsgthqH8=,iv:ycyV8mgHLacekSg53PiFG0Koa2ycQmKpinUdP38h66w=,tag:uX01/cXStFow+Uqo6BNkIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
