apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:4vdL9grC23uYgDvXKy2EkxnLPb7ZJq12YWQeboEI6IpcYkKuYceCDo7NZu2cqvF2sFhMrF3XyCRLJTkg04FLaLXupv3TNk8axOuLow1aW/tvAjUs0qRsfhDX32fDf5f0i/lbSje/boM16wKcpMzudFCX+y/U/WTwIxJ3HuxVPD2FaZuV2A7oXYdlW3MM,iv:BZp12albc3LgKf+x2TjrCJrTFI0USGFb+yNS1xzRwB4=,tag:vPnRTIXeOc9gwyruXqmCXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQzJtWjBEcFhtRmo2aWJL
            aFkxUFJYOVQ0YUZxa1lTSGhjbkRxcUIxL3k4Cm5KUzB2SUdmdFAvR0tVR2tMT0FT
            VzZXRjFrMXFUVS96M2hIMDErdS9hYVUKLS0tIC9QMGx1SDJEaHBWMFV1UTgwZDFt
            OU10MS8zMjlCRmxxMmFNK3BTNFdNSWsKBf1rIdyg61CKpDq43B+IJUi2jB34zCcd
            lMekc5zEB30DctBG3ygISSBiWJE7lM50aFzApgq48el0WhxvmV0dXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:55:38Z"
    mac: ENC[AES256_GCM,data:pKI/YB6uUzFQI3Ayx4jS0lp1rCxLXYKEMe72ArmnkXrzOIehj6c6/bUSiA1Dq7h6+g3t2vNjcQH17JXuIYP+gFI++QD8LFpwLP0YM7zDHxrFT33l+lcalAqkVmgg88WgqrDbW6kQ3hRLnBtsnrPriwwHRtuG9i6UCcBVzWwf40w=,iv:l5v+XPImTdW/WK2kKVmBlULpOshE7khUCkbvL6T/3tc=,tag:kXBuF/qf5OMZWLG4z/QvFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:amngh7PnxaWieXn8,iv:QuENrd5L4+nB3WbFOVkqvz/KbUcUBwzMoEtbsu555eI=,tag:2dj92qRpkqBRYo0unyKI0g==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:+gHtZN8KkHwJ31fkingcXQ==,iv:zSPCxMzNVxkx9r5m5OyFwbwUpl2+FRAAt8QiCnKkF84=,tag:wIih2g8YKDHlAVF3a6YdNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQzJtWjBEcFhtRmo2aWJL
            aFkxUFJYOVQ0YUZxa1lTSGhjbkRxcUIxL3k4Cm5KUzB2SUdmdFAvR0tVR2tMT0FT
            VzZXRjFrMXFUVS96M2hIMDErdS9hYVUKLS0tIC9QMGx1SDJEaHBWMFV1UTgwZDFt
            OU10MS8zMjlCRmxxMmFNK3BTNFdNSWsKBf1rIdyg61CKpDq43B+IJUi2jB34zCcd
            lMekc5zEB30DctBG3ygISSBiWJE7lM50aFzApgq48el0WhxvmV0dXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:55:38Z"
    mac: ENC[AES256_GCM,data:pKI/YB6uUzFQI3Ayx4jS0lp1rCxLXYKEMe72ArmnkXrzOIehj6c6/bUSiA1Dq7h6+g3t2vNjcQH17JXuIYP+gFI++QD8LFpwLP0YM7zDHxrFT33l+lcalAqkVmgg88WgqrDbW6kQ3hRLnBtsnrPriwwHRtuG9i6UCcBVzWwf40w=,iv:l5v+XPImTdW/WK2kKVmBlULpOshE7khUCkbvL6T/3tc=,tag:kXBuF/qf5OMZWLG4z/QvFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
