apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:69eVo2UYaRKn3rfBKEssfM8KsgtERsntmkS7BnWk1s0bUnRZ3m940DLjxq3jTnMAwP+2XBFN36PSHUivU+hRn4NSvCZDuHGqPf0pXmK9wfDd08GoJcfHQ1nlqYxM1XrQKiXzBkITw2fN845a3hSyIArQvh67+4mwOQgI+pMHSJNb4+I1+5s1WyYCMNjV,iv:0L/tywt8tNhywrDOYezv9sb9LCPKnRbPHDSICRwrk28=,tag:1+VyDqdd6jceEwwGTQAq+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMUoyRnFaUE1wb1VoQXcw
            YVBkR3l1bVVBU0syT1M3TDRlaVZYbkNXdlJrCnM4TkExYnlaTWFwU2sxTnFXMnBx
            bWNvQTAwb0VxM09jWW5jdEQ5TDRJT2cKLS0tIFdJaW93NjF3bnFZT3lpQTR3cFFz
            WEhWU2h5dW9Zbm1sSjVUMi83M1htUWsK+M8z+X07lNJoNLCkBXBjMpUAno8ZJDUV
            6cFk04BAkDQh7i7/9wbBqpwDoflPQZTPg+1BDFeDNTvPsusIMWqBKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:mKegFhOcUI2Dl/C+11tvmMbWYYZKjQgRoJQkvbSkoHSY/bzlYxbw0/dltO2OMvpVpWpaL06pARjKHdqb5HTua/aNlxb06XrW//91PSXQd8DdmpVz2EMbr8b0HWX9ODBZ8Wp1Tyze/al+FbrMJICrM+HOtrAxgB+trYo06H11gZc=,iv:GSewhknOxCGxkrhZEwE14H/SuvQ94kmAHD1hO42ipqk=,tag:oo96NnI8OrvNVTFEjMpgdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:fNdyEXwgwClPt0ti,iv:orbO0aG7e/ZokgQ/elw0RvhmetRl7W/75ldWAGW1mso=,tag:+FOBdqZMF6ARD3mzTJUBLw==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:kvY+zAXHf6Nidx+0ppsubw==,iv:N9ZbeX7grtXIZYdjwybYVbWsHi5LYVUBlY9Q7wEcc7o=,tag:ob21i0YIZmkmA/GuQ3dcAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMUoyRnFaUE1wb1VoQXcw
            YVBkR3l1bVVBU0syT1M3TDRlaVZYbkNXdlJrCnM4TkExYnlaTWFwU2sxTnFXMnBx
            bWNvQTAwb0VxM09jWW5jdEQ5TDRJT2cKLS0tIFdJaW93NjF3bnFZT3lpQTR3cFFz
            WEhWU2h5dW9Zbm1sSjVUMi83M1htUWsK+M8z+X07lNJoNLCkBXBjMpUAno8ZJDUV
            6cFk04BAkDQh7i7/9wbBqpwDoflPQZTPg+1BDFeDNTvPsusIMWqBKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:mKegFhOcUI2Dl/C+11tvmMbWYYZKjQgRoJQkvbSkoHSY/bzlYxbw0/dltO2OMvpVpWpaL06pARjKHdqb5HTua/aNlxb06XrW//91PSXQd8DdmpVz2EMbr8b0HWX9ODBZ8Wp1Tyze/al+FbrMJICrM+HOtrAxgB+trYo06H11gZc=,iv:GSewhknOxCGxkrhZEwE14H/SuvQ94kmAHD1hO42ipqk=,tag:oo96NnI8OrvNVTFEjMpgdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
