apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: |-
        export MINIO_ROOT_USER="admin"
        export MINIO_ROOT_PASSWORD="F.g98_!DR_g8"
        export MINIO_STORAGE_CLASS_STANDARD="EC:2"
        export MINIO_BROWSER="on"
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: bWFycmVybw==
    CONSOLE_SECRET_KEY: Ri5nOThfIURSX2c4
