apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:v4jpzsTRhlJoegg7fevyEs41alM1/gRnrX9ZvpuQypuIpzmtKKaRDuFSojkA71gxQcjb8/m+fZ3emjgC4noh2EjW8hgCEjRFVnX0OM7LFoAOl2kgNB1o8IkQWQiLClbljr5IqcByf+iDxtiZRFOEPL/lkRTYN1GVQzPH/25+KhA3sNdQcO2/EWjA4MZc,iv:sbVqB14HVZgpppobmENQYR5+y0G48dyxKpHmt/tlKsM=,tag:dFDJgWzwE8vOEbjeCJkRwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUtXdHMzME5qTWlOM1NR
            Njhlb0tFK0doZElTNVdaR0Z2N3NWbGJrem5BCkE3QTJHU1k4MFpiSlhYYUNqd1JQ
            bEtYRFluV0thdHVFcUtVa0pmYTlqb2MKLS0tIFRNckhGUzU3YVRMZ1FndXppTWRZ
            bDZCWm5KUVNYQ1c2K25JUnkyOUdxMkUK8YsVu+A50Y33ONDCzO5iRodQcQNMY2e4
            JJ0gIhLIejJs/Jb739/h/8uOonC5IwUgOVF7YZKXXkyTNtJ6eAFrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:Ovcl1g1UTnJJ3toIDDjTtcpVyIFp7XhcL72xsZWBWpNFaGIpa+7gZ7CHn3NsqPYmaT9ZXcm8BY6Eg6Mk4SKYX9puvrB5swlvEUuCANIkUqM8nPDGt3WQrs0BKTKn8i1ZTbaG21ZbyA2xKj/JspRZo9SAK7IXWdrB+4ZhXuaVlbE=,iv:ZaoZNLQjS/sdtGiwP3s+CAlFUedhTZ33K7roR3vcSrA=,tag:5jLMMEMSk6Fgok+irAnJVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:mqG+6jN+WIlTBPlS,iv:er3c5nIAKP3srOm+nP+CcDseHb5yzrMo/9Ia6Wt+UbQ=,tag:rpWi9sEs5B8nxUOhJmnV3A==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:JG+1z/VorEc8PTDqSLFs5Q==,iv:y6nMi5tju8MLQSos9Zn93N0LMa7fYaBEvXGJivp2N4I=,tag:qOyTF5ayOuFhNNHuKmvhvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUtXdHMzME5qTWlOM1NR
            Njhlb0tFK0doZElTNVdaR0Z2N3NWbGJrem5BCkE3QTJHU1k4MFpiSlhYYUNqd1JQ
            bEtYRFluV0thdHVFcUtVa0pmYTlqb2MKLS0tIFRNckhGUzU3YVRMZ1FndXppTWRZ
            bDZCWm5KUVNYQ1c2K25JUnkyOUdxMkUK8YsVu+A50Y33ONDCzO5iRodQcQNMY2e4
            JJ0gIhLIejJs/Jb739/h/8uOonC5IwUgOVF7YZKXXkyTNtJ6eAFrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:Ovcl1g1UTnJJ3toIDDjTtcpVyIFp7XhcL72xsZWBWpNFaGIpa+7gZ7CHn3NsqPYmaT9ZXcm8BY6Eg6Mk4SKYX9puvrB5swlvEUuCANIkUqM8nPDGt3WQrs0BKTKn8i1ZTbaG21ZbyA2xKj/JspRZo9SAK7IXWdrB+4ZhXuaVlbE=,iv:ZaoZNLQjS/sdtGiwP3s+CAlFUedhTZ33K7roR3vcSrA=,tag:5jLMMEMSk6Fgok+irAnJVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
