apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:2u5/tIHajF/DsbR9wZ9GKbqIK8f6RSDFVhg6zhgb6fkZX9HovH39JVzT2s7g+64YPVaQkQLOLrtJhK3vNxRU5cbSq0nqVh8UN3jaMgnrsIz7SpAcjZoWqku2EanCd2I2VA3kEJM8Q2kZhBRyw0Pf+fgizgZONI9pX7piYtoifmnDnjmj+7zJBEHLT/wk,iv:SodV18UGyEJr4W5DaiDzWz7+oRXCPbA9o2cTcK1JnZA=,tag:xkhvlLO7q8o1+mD07gyxUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySXB6T0ltRTMxZUlJWXRS
            S2JkT050YzR3bUlZUTBTakZ4UmxETFgwVWdVClNEbXB3QjBITVNXdEVEZDFzelM0
            VkdrNm9DVnErRnhxTzU0K3laU1oxa1kKLS0tIEhNM3RxVGsyR0xCR1lNaVBFZitL
            blpjekJDNnBFNE5leCtzMTFWSDM1SzAKjVWBLM1w1aQ7RjX8N0iQFj+wpfwVvkn5
            DvGhUJDl6BU4/iDqedrmPvl97+Dco8+IBus+Q2fvo1TOfERtuzmzJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T23:22:50Z"
    mac: ENC[AES256_GCM,data:EGTAD2jCwUTzaVGI9l/3V9u60QR1L9f9aUeS/nFPZvCwEPK6PeGkJELs52wpsHDWiNkS+I1jMDTpeJefttSQtyVFvKXmwTQvBnTGGU3FTDOKJr4gsSNEYpC5CLoYKOwo1MHQ7gLWZL5t23GsQA2FxO8sTtkgTkzn5y2bzNhZqlQ=,iv:Xam6HhFWLQizEFgn0x1zMfR5LQJDXnXad47FgvdFi78=,tag:2CTlAmToMMb2ulpMK1atGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:5qxNyJzkcX8STu9e,iv:3msOjr3YWiPyDFjhTOuXSIUizvj9++iTrQy8dV99IU0=,tag:JCcWGkSvyob9liccEpfCNA==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:SNQKOwTThph8jQXzk/gw5g==,iv:2OEnbTNbQSt7j0SJOmlXb65s5VS/0wxcGdi/ROcYe1U=,tag:7hfA7lnachhwXjKesqwaPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySXB6T0ltRTMxZUlJWXRS
            S2JkT050YzR3bUlZUTBTakZ4UmxETFgwVWdVClNEbXB3QjBITVNXdEVEZDFzelM0
            VkdrNm9DVnErRnhxTzU0K3laU1oxa1kKLS0tIEhNM3RxVGsyR0xCR1lNaVBFZitL
            blpjekJDNnBFNE5leCtzMTFWSDM1SzAKjVWBLM1w1aQ7RjX8N0iQFj+wpfwVvkn5
            DvGhUJDl6BU4/iDqedrmPvl97+Dco8+IBus+Q2fvo1TOfERtuzmzJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T23:22:50Z"
    mac: ENC[AES256_GCM,data:EGTAD2jCwUTzaVGI9l/3V9u60QR1L9f9aUeS/nFPZvCwEPK6PeGkJELs52wpsHDWiNkS+I1jMDTpeJefttSQtyVFvKXmwTQvBnTGGU3FTDOKJr4gsSNEYpC5CLoYKOwo1MHQ7gLWZL5t23GsQA2FxO8sTtkgTkzn5y2bzNhZqlQ=,iv:Xam6HhFWLQizEFgn0x1zMfR5LQJDXnXad47FgvdFi78=,tag:2CTlAmToMMb2ulpMK1atGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
