apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:jc7YoExX/tx4mdLslTJONh53VS9kNAfB+J2i72PhUXTCHCPgTTtmPs3mqT5OnE5HBURyXUg31pxoq/KH/nL/Dt2DyIhN7qtOhcC25XkdkUASiI1ObOko/qmlAH9bYPkmoo6Ch/i9OskiUnOw0wKAVCw3Uttzbg9/sp9qjKa1ktSsvvVYLf+Y1L/WxQQR,iv:yS4stIbr+kSqCgQyhwrlIGBVQHH68EPJEMyKPNvoEms=,tag:xuEscpItwrAQ2WTohm0m4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY28yY2l2TmJxZUNIMlJy
            bzkyOFdlTDdIZ0lrRDBnRjBkL2lCaWFBNkVVCnRUYm8ySE4rM3hWNExpS3Y1TVdh
            aC8zN3ZZT3Rac2t3R0VDMzZLT0QyZDQKLS0tIEV3Q2dhTmhSUkJxaytrdW1TWlA3
            TXR5SmhOV1lCOHNnV21pR3d4MnB1NlkKZbhrP7nfIAOt5BFZnx2SJvYvegqKqkMK
            r4zNkacSIzKxFXqzd1yS6hhvqtZ/FU7I5eR6MZ6EVhNb5iMei1XXGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T21:02:25Z"
    mac: ENC[AES256_GCM,data:p+DRG3i55HKL+M0yyWB2F8rjjJfIk6RZ4A2YuYBTTSoMTwPxeHK51NOHgnAocKuD769hpIiRugfpc5j2C8aaMhNMBK6i3liAnrEyp99rsyXSN3YuQ32u6QMwkdC1yLRjphTST5/HRgc5Pkz5qWwSI55bMf8+ZsJdDo4FIJ5O+RY=,iv:I4bJrkmGgHLL8imjVT+AUYqc0lE/FGhx9OwTPAWUE6c=,tag:OjpF9+m5HA1gcLtPIaaG7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:sWVN6j4pYwIfsZ7z,iv:SSa36EN2HlUE5chPKloJ4tat8x+wIinCXF6kADRmgVo=,tag:n6JPNDIwxNEtZFz24Rq/dQ==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:PlssLY+f4jUQZsrZ5TIgmA==,iv:dv+EDkElpmUhx1EZv4faMrt72TsTmHW2v8OWf7upMBQ=,tag:GfwppQBEf1BH9yxD8NZaEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY28yY2l2TmJxZUNIMlJy
            bzkyOFdlTDdIZ0lrRDBnRjBkL2lCaWFBNkVVCnRUYm8ySE4rM3hWNExpS3Y1TVdh
            aC8zN3ZZT3Rac2t3R0VDMzZLT0QyZDQKLS0tIEV3Q2dhTmhSUkJxaytrdW1TWlA3
            TXR5SmhOV1lCOHNnV21pR3d4MnB1NlkKZbhrP7nfIAOt5BFZnx2SJvYvegqKqkMK
            r4zNkacSIzKxFXqzd1yS6hhvqtZ/FU7I5eR6MZ6EVhNb5iMei1XXGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T21:02:25Z"
    mac: ENC[AES256_GCM,data:p+DRG3i55HKL+M0yyWB2F8rjjJfIk6RZ4A2YuYBTTSoMTwPxeHK51NOHgnAocKuD769hpIiRugfpc5j2C8aaMhNMBK6i3liAnrEyp99rsyXSN3YuQ32u6QMwkdC1yLRjphTST5/HRgc5Pkz5qWwSI55bMf8+ZsJdDo4FIJ5O+RY=,iv:I4bJrkmGgHLL8imjVT+AUYqc0lE/FGhx9OwTPAWUE6c=,tag:OjpF9+m5HA1gcLtPIaaG7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
