apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:qmYYmFkMo+QeydEDt6hOHVKge5m0U3D08dNDNOwcq+GTESXsY2PANa0W0iNzIwc/dEqrIYigi98TBQGpSI3Jlmq+TRdV/seAU8SLI13utaA/PYkpJlNSczcNCRld1qNbdOvpLe9j6jkPbn9d/w6Y/o6S5NjxGg5dgfTnJpIrTbq271ztR6TlzG0PfakY,iv:8m07TuYNrXkJ73zacMmOGyPfnYEratnGq3dQ43lswnI=,tag:Rmng2Gg9PcmQ+uG1f6cCdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU0QycTE2NkRGWTNtemtB
            eEVsaS9QdXpHa1FqWE9RYlNTNEpVZGJyblhNCkVDTTJ1YnhHRi9oZ1NnVXJyTkJt
            bUdqa2h2bll5QXZGMHZkbWw0NllJbVkKLS0tIDhaMWRITEo4Y2lBQWV0YmpsMU15
            Q1BONHNpaHQwWW9FZFM2ZzZHLzdwMUkKiOfwRO/Gd0s/pDlQGUvPw+n8b4TShQFH
            y8vxw1HVCqtISAeUF31kNkgcS+J5q074refKhyXRhCDLfdJjCw9WQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T20:21:37Z"
    mac: ENC[AES256_GCM,data:AM4viCbX7ICMZKGhjAn7evYBP+Edy3r0X0cbqfjW0DXl0GQL8dl4qPYnuvLMgGpGTn0+rBqSwuOdZiBTygl4kg1WE18dYovROYCJth/PTqd007c2HAVoLwHfWvrV9ZgYkmS5iQM1g3n+vfOF4Sby4NIpAe/sxO7wFGCQbVz9mUk=,iv:LNg1Vnoon8qRFs5ToE79I8NQeWer6HepC7wyEiiLkGs=,tag:cxPxVlHHnVBAdVhqZHwV/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
type: Opaque
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:+9MnUeEDTQS5kWgc,iv:1i5F4x4BperFvIKGRVgvpL6ubsSuEipwSvw0w86cW+I=,tag:Q/qM0udIoYNVRe9oYjOXAg==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:vkgCKE0LHQUhaZSfuU3O8w==,iv:+gdBPmDxkZ1aJQrJbKrYV/AAiVDZzQ7iaVTBEKPV09Q=,tag:GxhfUGO09p00eApriORl0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU0QycTE2NkRGWTNtemtB
            eEVsaS9QdXpHa1FqWE9RYlNTNEpVZGJyblhNCkVDTTJ1YnhHRi9oZ1NnVXJyTkJt
            bUdqa2h2bll5QXZGMHZkbWw0NllJbVkKLS0tIDhaMWRITEo4Y2lBQWV0YmpsMU15
            Q1BONHNpaHQwWW9FZFM2ZzZHLzdwMUkKiOfwRO/Gd0s/pDlQGUvPw+n8b4TShQFH
            y8vxw1HVCqtISAeUF31kNkgcS+J5q074refKhyXRhCDLfdJjCw9WQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T20:21:37Z"
    mac: ENC[AES256_GCM,data:AM4viCbX7ICMZKGhjAn7evYBP+Edy3r0X0cbqfjW0DXl0GQL8dl4qPYnuvLMgGpGTn0+rBqSwuOdZiBTygl4kg1WE18dYovROYCJth/PTqd007c2HAVoLwHfWvrV9ZgYkmS5iQM1g3n+vfOF4Sby4NIpAe/sxO7wFGCQbVz9mUk=,iv:LNg1Vnoon8qRFs5ToE79I8NQeWer6HepC7wyEiiLkGs=,tag:cxPxVlHHnVBAdVhqZHwV/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
