apiVersion: v1
kind: Secret
metadata:
    name: spark-env
    labels:
        app: spark
type: Opaque
data:
    CLICKHOUSE_HOST: ENC[AES256_GCM,data:3cXZqm32HBWGFE8q5sTPRWT4VDvvYOtH,iv:FKrBa1Cym8l2k2+wZczr8Y++kOiCk+1DBorzCAcZzrI=,tag:ORZvJT5iUwZUzDSXodfOlA==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:RvEboT/v+q5a2aba,iv:dwUjV5MK2xMMJak1yd3BhaHQRjNq/V1np2cOhDtcHIk=,tag:l0a7dDiNgxg7i76ptzyFiQ==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:IMVeDA0flhf7iTlStCdLgg==,iv:BF81z/f+h6Hy0iIo7JNH5RDKuX0dB3k68d1RaiBu1yg=,tag:kSdeeTW/PIHQ3pt2tB3Sog==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:1dg6DWdn4JySCUn4,iv:mWOO6hROiGZXRpnX2fSZDPUq/hbmdi5yH9qZq/k+ERM=,tag:erqQUum6KZX2VVa67S++jg==,type:str]
    NESSIE_HOST: ENC[AES256_GCM,data:XROtgdFYX3Q=,iv:+Dmuqu5izaMlxtXExexJQ5mFfISVwD1qRL8z11M3HIc=,tag:fMI+j++o4hJkaZk8+lcagA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:vyhX4BUpH/U=,iv:OI00uPYDiY5xz2hi90xe1ykbpsJqHYfcpnxn+Mnn8Mk=,tag:kfTxVWNfwUC4l/wNa6eK0Q==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:0F9m99+Xu1GTmkHC,iv:CWvY7jORYwauFycd1tkb3e+2WlPGcFXFhT5hAvPfx40=,tag:b17brr0RINoYqrdtWHkjLg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:UZTKCOXgZGtiiKE+,iv:YAUnX6yfdZC6MkQJGQ+PZ49C1+Yy7sj7hhLLm8i6AQw=,tag:sDoKPlVFMi8HQC45MD6rbw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Gfu5SIQPw6S60+HNlG2n7Q==,iv:Zrv+/CXtoaDUA+LYo/q+QsmSQsEH9v8SS3tGHuaLOes=,tag:Q3wZMWqHjG+Zd0krL9SS3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZnUvL1ZsYkpWcGVwUXdN
            eDMzQzRjNy9WYTFNaDgxeTlkMFFiQnlRVWpZCnpEeE5kbHZWUExmbmtma3NxbTUr
            SlZVdEh1eVl0UmxDVCtDeG5QS2NmWnMKLS0tIFB5bTdMdXNUT0pZWkE0Q1RFNkJm
            cUFlVFNUdzNOd05ITVNZNmltS2dVUVUKd+TAgiDJKTZZVSCes/BpGMAS3gtzFInD
            UQBYadesP3EhEgidguKx6QGXmUFtYAHzXDqkoV4K2s4yPdvtxXu6jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T21:02:25Z"
    mac: ENC[AES256_GCM,data:PRe6AXa2YPKKh4PE57y3IKrqse/kvmR9TafKejXmRo1B4kkY6pXXxy1f0qxy2n+x1JbJH4lYPug85GAwqrZbuWakqYatlbeprq+3da00NkrNWXhpE0/giPSna+/D6KkzVXoWzY/PX+3EPU4q8SlTtJR2shoVHVxrqjAbqXU6r+o=,iv:DTSoXeNrqs4VDnFLHy/Sz9Yb+U67YsxSXltMj10VY34=,tag:ogEuy0OTC1aHthEcJJnJng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hhF/Cxn6jwETsPj2W2loka5ke4lS3X7TMaDf0Fnl3qNAR5JPiOJXzDfzEdnLBMNC933Tv1/MAQAic1eal3eanGLVN61S4aW1PaPdX64Xg2KqbN+dkVkO7EWpwqSF1nJg+RGw/4a0aL9hnI+FNdKmaoI/6uDdv0Q0a9jNiR5NV8CBhKiH,iv:cEg1UnAafFL4Wgz1Gsj+zPS4SGv/cNzYpsVAJOoUDIU=,tag:BN5+kCkVCSwmLKoHp0OBXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZnUvL1ZsYkpWcGVwUXdN
            eDMzQzRjNy9WYTFNaDgxeTlkMFFiQnlRVWpZCnpEeE5kbHZWUExmbmtma3NxbTUr
            SlZVdEh1eVl0UmxDVCtDeG5QS2NmWnMKLS0tIFB5bTdMdXNUT0pZWkE0Q1RFNkJm
            cUFlVFNUdzNOd05ITVNZNmltS2dVUVUKd+TAgiDJKTZZVSCes/BpGMAS3gtzFInD
            UQBYadesP3EhEgidguKx6QGXmUFtYAHzXDqkoV4K2s4yPdvtxXu6jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T21:02:25Z"
    mac: ENC[AES256_GCM,data:PRe6AXa2YPKKh4PE57y3IKrqse/kvmR9TafKejXmRo1B4kkY6pXXxy1f0qxy2n+x1JbJH4lYPug85GAwqrZbuWakqYatlbeprq+3da00NkrNWXhpE0/giPSna+/D6KkzVXoWzY/PX+3EPU4q8SlTtJR2shoVHVxrqjAbqXU6r+o=,iv:DTSoXeNrqs4VDnFLHy/Sz9Yb+U67YsxSXltMj10VY34=,tag:ogEuy0OTC1aHthEcJJnJng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
