apiVersion: v1
kind: Secret
metadata:
    name: spark-env
    labels:
        app: spark
type: Opaque
data:
    CLICKHOUSE_HOST: ENC[AES256_GCM,data:vf/lsS8J8huMXi515UNk24Jb3V+vPZEu,iv:7t20ROuKj9q3BNTVLey1PFB28vDbqxIC1oL2BzTR8ck=,tag:gXFx/J9/ZTcCEFWyyeDs5Q==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:evDIITcO1+YAVtmy,iv:E5KFjUB2AoWtmmNCjw9iUrOcsCxS8k4E2nuNC1KfniU=,tag:MG3okCZORg9aLVAv0d5CWg==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:0Sn2yPxJG7ZbbiM5QrdEYw==,iv:D95BmIbxK7K76HOWYfW7OlbzDvfclU3X1s8q6Cq6Qmk=,tag:fL1ea19P53t9d5Br45hs8A==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:+wukbZQPR0fKdysi,iv:KjWFh7tR6NSHAoGhpfhvgt3bRa8Fmp52Md91yZBjBbI=,tag:57hES63IO270u/wsWSZvBw==,type:str]
    NESSIE_HOST: ENC[AES256_GCM,data:5/fqQFtys6k=,iv:u1r0HEpceCU2M5a8p3cBOCgya1Pf66ymTjZ+CNNH6+4=,tag:ozr4GZ2O7rtULsAAzicMhA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:6BlJCrLx144=,iv:+8lis4XD2sXt1ksA7lOhavYwLytCmK94szW+chrQDr8=,tag:AOvgz9+NKG1df1OLOc6uqw==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:qUVNuopYoRrEx73w,iv:QZqEAhpcP29IJnplT+sLH3UQRf4i9ht+2cdPb7p5oaE=,tag:RxGviW1dHRN/v+8wtgFBNA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:h89fq9SquCLy/psN,iv:BIiNzXW2uA0e3B82oxO7/QEuttv9W2fJ+HxkLt7WkxM=,tag:626s0m87dkaLvdrI0qHjmw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:H4d0u+C+Ihm0ItycALgVpQ==,iv:IIRQ4Casg64XuCyu5KBWXBculrIEZczq9wsw8Hc2f0g=,tag:I81qR7FNgs6bkLqQ3JcIcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT0d1eGt2SzVyL1pkcXor
            MUxURHhab0FIbFB1bUYxNzdJc09wT2lOWVRzCmFiaFJNNnFGL29nbHVYWUk5K0pJ
            Zk8xbTZQcFMvb0piZFVQZ1l4ckg3aUUKLS0tIHF2T2F4UGQwWHdBN0JYb2ZqT1Z0
            Q1R3ZElTQ2RKMEJQVTB2OVV6dThZcFEKcy32CYU/yf1Z4ktfb9BGxSPlbcy84DV6
            Jqm6q8UX5WzyVvGJrmKWoaWlnYw5e7CX5Ll1q29JcI/5HVGKJ2wGbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:55:38Z"
    mac: ENC[AES256_GCM,data:jGjuLTuu9LHc7LHp32jHJhuDZrKjrGHPFmy0WS/Xc3XmZ8in91ZjW6qa4yzR2L0iGyt+cWdkf6cRl73WRv/qu0X+O36ajiI+Ru5WMxbKF4l0/cnHqjNVjZ8Ova7fNW7Tujb/yBYxwNY2n3BI5tEZJe0CiJRn8hs20Z2+zNIE24k=,iv:qqrqc8m4L/UPtmH1bpj8EYk8cJiOGnxBwlorU1Mufww=,tag:kMHTAS9Jqa+AB4qCtXAfqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:J1DTWtJG3VUR1O5hYve8j+cz8K/ADOzIJgNSlmWiWKZvD51nbjEo+/WUV1H22L1KcC9VhI0A7beGNyZzkIKwXJqLEYoSS6RwEmlGWsiA5BJ71hyU7MCfrJ8mYiHJoev0nG3Rk7INZxlIG+tyl41QxGHGQ1qRkzpudO6mxrHDLrt43UC1,iv:iOCN0WBDFlbQfZVrD+3bYGwg2PtP2zoZoN1iKWJlKKw=,tag:1I9uky+76+qjFdFSKonAYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT0d1eGt2SzVyL1pkcXor
            MUxURHhab0FIbFB1bUYxNzdJc09wT2lOWVRzCmFiaFJNNnFGL29nbHVYWUk5K0pJ
            Zk8xbTZQcFMvb0piZFVQZ1l4ckg3aUUKLS0tIHF2T2F4UGQwWHdBN0JYb2ZqT1Z0
            Q1R3ZElTQ2RKMEJQVTB2OVV6dThZcFEKcy32CYU/yf1Z4ktfb9BGxSPlbcy84DV6
            Jqm6q8UX5WzyVvGJrmKWoaWlnYw5e7CX5Ll1q29JcI/5HVGKJ2wGbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:55:38Z"
    mac: ENC[AES256_GCM,data:jGjuLTuu9LHc7LHp32jHJhuDZrKjrGHPFmy0WS/Xc3XmZ8in91ZjW6qa4yzR2L0iGyt+cWdkf6cRl73WRv/qu0X+O36ajiI+Ru5WMxbKF4l0/cnHqjNVjZ8Ova7fNW7Tujb/yBYxwNY2n3BI5tEZJe0CiJRn8hs20Z2+zNIE24k=,iv:qqrqc8m4L/UPtmH1bpj8EYk8cJiOGnxBwlorU1Mufww=,tag:kMHTAS9Jqa+AB4qCtXAfqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
