apiVersion: v1
kind: Secret
metadata:
    name: spark-env
    labels:
        app: spark
type: Opaque
data:
    CLICKHOUSE_HOST: ENC[AES256_GCM,data:cMn6luqfpQpC5OgPpYYvTiUSxrp0PkhN,iv:jL1qDcU7mK3HjXH4Tv2N43JizgmteN0aZSpdSLornRk=,tag:tjbZfZjo/TehNRK0JYYa+A==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:Ddo1dNsToIKI0CDn,iv:eHxgJvxGGFtzQ3ZZkU+iDyLVD+kfiO9qXCcqCewtiNM=,tag:mid7bFL676ygalW2Tm6tHA==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:015v8LdBzg7xID4it3PJfA==,iv:pEmiG42p59UdF6hOu1GxNR7syUdiUtm5tPSIKlXVEOE=,tag:h+NIL12w2gf/rHJaJRlNMA==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:lmyjPxqW1JVuWuky,iv:WoCSFkXx+k4/tV7rSWOmAgzFrGfIBVcf8VZob9WcGrs=,tag:gMLhRlkct7EukrsP4Fhs/A==,type:str]
    NESSIE_HOST: ENC[AES256_GCM,data:c2t/y0BdcsE=,iv:FVcZwc5Et51noF67sSA8pKMSLxeMCYOqcX2kwQR/838=,tag:3gei2uc9jFTTW/C6t+4uAw==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:zoK/K4wusR0=,iv:ItGh8/w/h6Xs1mYt6M+Z45eOWFdk2d5oRioR3Od+YYw=,tag:CLnjE8VBd639+ZUFI+aNqA==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:q0hKNge/0OKgOjqO,iv:Lmo+j/tWk78IhSSBJpwtJq0bV9WVq3sLGWAhz+7azIw=,tag:CNeMQck3bxiKq4XtIQZKnQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:nuzAUW82lfLBvsRt,iv:xgNAEDwf/AiVqCgY5M1F30ut7cWWoPfFZ26wfwWZiSM=,tag:PsAj8ZMf+HP+t9q4uHmUYw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:4dk4F812UIF5+mMB/7J4vw==,iv:FsKlOtUZYRUrSikE+pAuDjhxxkVQwB+YVC3zQwxpxe0=,tag:6cpWcSOl0BBYIhvUdjrh3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NkJZZkhMOFlhN0lXTGpV
            NStLT3ZHU01VbjY0cTJFVGFUazVkcGlaZTBnCnp2SHA5Q0pyaXlRc01vTFJsc0wv
            azIyTE9wN2Zqc1pBTW96QmJlaEhvYWcKLS0tIHdGZFlXVkpRT0lCRmlOWHJCMnA0
            K1JyTzRwUkJHRzI5N3JhZ3RHbThDTHcKL5VA46Et9JBhRU4msRkL6ibbltZjW4UD
            Qz0hM05duJOFAbfJEF1nC2fgvuj8Kx+kCyhEbUVm15oKTZdFGbA5lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:CLoWRuNvqsKIXvt9r2XkSs3tp8+aPe6+STqXUI6E+nbsPKZFQsTI3WPmUYbiNrstE6Hexu24rIjPCK3Z2NiYpBHrTZPwUMX4XflkJ5/YDkzLfw8hE8fncpSKSEzm1RLjMRvASlhTLE4Kl54keTuq9TiCRs66knPy4KtaygjPRqQ=,iv:oZUTod0N8Stycx7SEJMhhCNLc6cmTnNouFGNc2ZRfiE=,tag:+lQIlMJfaZAVOmiPqmtB1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:sDgC/hNCDGAbnek2s2AsaFLShGdkf82sfGKWyh2utgLBwxVuFaIw6l5/AKhdbCFVlDPJwtW1JIolAiL2iyG0XntPp/fhePFW+sHcl59gbWJAys0xojgSB5RTXx2WN9mCHZcEs+gTObCUX8i2YRSEjsiOLA18k8EPNpzeqiEU7NaUDrOR,iv:LiX72SQdj6u7RFtAsJHcFpEfpKgpQB4HHErazzY7beI=,tag:hFDk5nQ06/ekaftGbIMhtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NkJZZkhMOFlhN0lXTGpV
            NStLT3ZHU01VbjY0cTJFVGFUazVkcGlaZTBnCnp2SHA5Q0pyaXlRc01vTFJsc0wv
            azIyTE9wN2Zqc1pBTW96QmJlaEhvYWcKLS0tIHdGZFlXVkpRT0lCRmlOWHJCMnA0
            K1JyTzRwUkJHRzI5N3JhZ3RHbThDTHcKL5VA46Et9JBhRU4msRkL6ibbltZjW4UD
            Qz0hM05duJOFAbfJEF1nC2fgvuj8Kx+kCyhEbUVm15oKTZdFGbA5lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:01:43Z"
    mac: ENC[AES256_GCM,data:CLoWRuNvqsKIXvt9r2XkSs3tp8+aPe6+STqXUI6E+nbsPKZFQsTI3WPmUYbiNrstE6Hexu24rIjPCK3Z2NiYpBHrTZPwUMX4XflkJ5/YDkzLfw8hE8fncpSKSEzm1RLjMRvASlhTLE4Kl54keTuq9TiCRs66knPy4KtaygjPRqQ=,iv:oZUTod0N8Stycx7SEJMhhCNLc6cmTnNouFGNc2ZRfiE=,tag:+lQIlMJfaZAVOmiPqmtB1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
