apiVersion: v1
kind: Secret
metadata:
    name: spark-env
    labels:
        app: spark
type: Opaque
data:
    CLICKHOUSE_HOST: ENC[AES256_GCM,data:rv3Ysdr/Y72xK2xHw3NTotvxaSqsAw5P,iv:mCXT7utfoGpQiaraKnTdLShg1i1qtT30UojEuOi0XPM=,tag:qud4n0xR3iMH1uXbwHZK0w==,type:str]
    CLICKHOUSE_USERNAME: ENC[AES256_GCM,data:+RClpgIhIsWsmQ9x,iv:H9fNFSSn6W8CTjdxoZAMr/xJKwyI0rnxP4csnG9hJ2k=,tag:m3I4hPL3YE6+T5N15XZV8g==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:BOvDJlDYsS3Q2x1UvLbzuA==,iv:GAj5O70rmwNfIFXYW/QXgm78ZTQusdbbMTe2At8vM7s=,tag:kcswnbx1SIrIYGFttKUe5w==,type:str]
    CLICKHOUSE_DATABASE: ENC[AES256_GCM,data:cnd7DlcrOlgI1YBT,iv:MyyKZXdhpRnivKVy6jT2zdxpfXwqHUKMXti7wSiGITU=,tag:PPdCzslTIKcdwx8fA+WilA==,type:str]
    NESSIE_HOST: ENC[AES256_GCM,data:iP+RFUuyOFc=,iv:OFQQjVQKV0JrUbmvp0owE2fkOUr4ZSfAGBVPeJ+mpNw=,tag:7RW0rPZjgoaK+nSPYqEFcg==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:eXx2UXH4Qo0=,iv:JtRpSiIQ+U0HpGkwjFq7vM9iVZ+p41fUEWC0rvl7M94=,tag:vqWWd0LcaQMpRbYtuBnaXg==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:eEes1CG7xjWiDD0l,iv:eNsDRc7Gp1BfqT0WpGmam1iBsuZrUTl9sUVfXnmR/40=,tag:yySExtPf+87sDi5lWoEVXg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:56mx9/z4A87Lk1uw,iv:LIIAMtjmbvgPc8dSj/ojNkHY/1fAohUrLpznUlmFs/A=,tag:jgMqnGsmgSAf9qM/uWVh/Q==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:30Bu/w7I1weXUAUzXCPSkQ==,iv:U4bM/1DynIhUUdt8LfRns5oHCXnDPe+OUq/fMd3MZtE=,tag:OoIRfsilUIrp99zkbSOeew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYStwcHVtbTZ1OHlTSmZn
            cHBGdTZ1ZkxFM3lOemQ2UFJReWlROGZ4cHdrCmxzMTg1THc2VmZPeTJCOU0xd24r
            Q2RZeXRIdU5CRUJyZmhUVVd3N1QzTEkKLS0tIDYzVHFQblVUM1IzampEMlRkTE9I
            YWRFc1oyUGlLTk8yU0M1ODdUMW1aREUKMXaXIf0s1Gii+RvNrrjjPoJRE0+j3Kh9
            jrLO6BbkqxM6Pl8tWXvHoiM0XcA+rLhIwJkc9lYqFoZAnvw4Jg/F2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:NyxSEeyFUAbFdJPDj5VZiWyG3uvyZDvokhR/lnqxL5FgA5KvG0hI4a0UedVrYNKonU9onxW0Is7xIiemqnpzsjoOZ4usYqgiuEvAVeYgCE/AI+XjvNjOBK2PDBKmI5Jw/woG2YN8safTDsenzcN2f+8cQiRNDANOf//JIbGT31c=,iv:X2h63B2jKKerEwzEg5Gee5uuPiWbEB8mrENAg+O3fVU=,tag:FlexSvte0avZdw/yAnQUAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vD2q4tQPh2z7lsCNl4I4U6iEtGHh2oYDjmBuZ6B2yj+olGQ2EvBSkW6d8GXKAl1fAX5mrb8qbTbazt4oaIz9OYpr3refxDBCqBsgDLGq2aLAlmQ9Ch32SFWN8poDO2kLJdBF5xIH+Txn4U+KvxGWhgYzs2glFbg7MTkgOqiSUrVFRBTN,iv:NgRPEuJARaXvC43EnVCN4IM60GzE9Mu7l+btSyDi3hs=,tag:7vI1uWwDjWC+rB7rpf1MtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYStwcHVtbTZ1OHlTSmZn
            cHBGdTZ1ZkxFM3lOemQ2UFJReWlROGZ4cHdrCmxzMTg1THc2VmZPeTJCOU0xd24r
            Q2RZeXRIdU5CRUJyZmhUVVd3N1QzTEkKLS0tIDYzVHFQblVUM1IzampEMlRkTE9I
            YWRFc1oyUGlLTk8yU0M1ODdUMW1aREUKMXaXIf0s1Gii+RvNrrjjPoJRE0+j3Kh9
            jrLO6BbkqxM6Pl8tWXvHoiM0XcA+rLhIwJkc9lYqFoZAnvw4Jg/F2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T18:23:13Z"
    mac: ENC[AES256_GCM,data:NyxSEeyFUAbFdJPDj5VZiWyG3uvyZDvokhR/lnqxL5FgA5KvG0hI4a0UedVrYNKonU9onxW0Is7xIiemqnpzsjoOZ4usYqgiuEvAVeYgCE/AI+XjvNjOBK2PDBKmI5Jw/woG2YN8safTDsenzcN2f+8cQiRNDANOf//JIbGT31c=,iv:X2h63B2jKKerEwzEg5Gee5uuPiWbEB8mrENAg+O3fVU=,tag:FlexSvte0avZdw/yAnQUAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
