apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pv.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml

helmCharts:
- name: nessie
  repo: https://charts.projectnessie.org
  releaseName: nessie
  
  valuesInline:
    versionStoreType: "JDBC"
    jdbc:
      jdbcUrl: "jdbc:postgresql://nessie-database:5432/nessie?currentSchema=nessie"
      secret:
        name: "nessie-database-creds"
        username: "username"
        password: "password"