apiVersion: v1
kind: PersistentVolume
metadata:
  name: nessie-database-pv
  
  labels:
    type: local
    app: nessie-database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/mnt/nessie/database
