apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-database-pvc
  
  labels:
    app: nessie-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
