apiVersion: v1
kind: Secret
metadata:
    name: nessie-database-creds
    labels:
        app: nessie-database
type: Opaque
data:
    db: ENC[AES256_GCM,data:KcD3GYtHRo0=,iv:7MfY61pajXLtdIyAHpa2guq/gBR2/WpSCGekrUHw9SE=,tag:M671XQXWzeQi93Wxl8j27w==,type:str]
    username: ENC[AES256_GCM,data:qT2Soejw9lQ=,iv:Mt6fe4gMBcaHKwEcR9Cl9iEU+j/FqtUkED8HoCfWzXM=,tag:DqfmkKNo64OBlItz4c1umg==,type:str]
    password: ENC[AES256_GCM,data:bcarwU7QIC7eny7W/KMeXQ==,iv:0WtJtMdFvBl9RinpruAo5bbdL0pXd4hUIOXDjmYLc4M=,tag:TEn+qWFCxBZEsoNnvzY1Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcFZmZEpJMUN2T0o1bHBv
            UkNUY2F6b2Q1My9IQ1BCZnVIT2hBL0ZHaXlRCmlMOEh5akJIWVI2dXQyMzNzdVFM
            a3Q4VUpGOU14VUxrZTlva2hzOVlFS1UKLS0tIHN3cG5KVm5aR21WZjJpRGtFN1R0
            azI5Q3BSR1ZyL1A0dnYxYU0zQ0g0WnMKsTXbnPYb/eazrrW2i/Lg9v30cWm3xIOs
            bbKBmENJCbxg6PUaBW3XYKZumufWIN3QCbt0VXQ8q3/9yBqOKCM6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T23:22:50Z"
    mac: ENC[AES256_GCM,data:BLXl8SOXdlpy6OxPWFTxHXdQMJMy2oV74r9At/OJ9wYQpZH6YLkZPvWyEKDR6AfdrMZYMx5gkZXnh3xa2rhA3pYgEG29wujf7RRLRbnL1BTcxgTK87EB6uM0AcDCWBj2WXMow7ZvVa1ZwJMFfvm6duOLCBad8Tyyc9zX0zBSN90=,iv:nvfMVzb9dLNtiLgdnKTqHYz1di1cevO0pJCfsyUiD3Y=,tag:+aJOmgi6D5rMD61tch7Hxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
