name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Spark Base Image
      run: cd docker/spark/spark/; docker build . --file Dockerfile.base --tag sparkbase:$(date +%s)
    - name: Build the Spark Image
      run: cd docker/spark/spark/; docker build . --file Dockerfile --tag sparkbase:$(date +%s)
